### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by hirbod** [lemberg/laravel-code-style-command#1]
```log 
  Problem 1
    - Conclusion: remove laravel/framework v5.8.3
    - Conclusion: don't install laravel/framework v5.8.3
    - lemberg/laravel-code-style-command 1.0.0 requires laravel/framework 5.4.*|5.5.* -> satisfiable by laravel/framework[5.4.x-dev, 5.5.x-dev].
    - lemberg/laravel-code-style-command 1.0.1 requires laravel/framework 5.4.*|5.5.* -> satisfiable by laravel/framework[5.4.x-dev, 5.5.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.8.3].
    - Can only install one of: laravel/framework[5.4.x-dev, v5.8.3].
    - Installation request for laravel/framework (locked at v5.8.3, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.3].
    - Installation request for lemberg/laravel-code-style-command ^1.0 -> satisfiable by lemberg/laravel-code-style-command[1.0.0, 1.0.1].
```

neither with `--dev` nor with `--prefer-dist`

**Comment by hirbod** [comment]
Might be worth to mention that I'm running Laravel 5.8.3 - support for this version would be nice.

**Comment by bkhrupa** [comment]
Hi, @Hirbod

Thanks for your feedback.

Oh, my first ticket for public package :)

In fact, I wrote this command only for my own needs and even could not think that someone was using it :)

I added support for Laravel 5.8. Please upgrade your laravel-code-style-command up to version 2.0.1.

**Comment by hirbod** [comment]
Thanks @bkhrupa 
I ended up using PHPCS-Fixer 
https://github.com/stechstudio/Laravel-PHP-CS-Fixer

but I appreciate your work!
